# Data Exploration

In [1]:
# imports
import pandas as pd
import numpy as np

### Merging Tables / Collecting Data
---

In [2]:
# importing products table
products = pd.read_csv('../data/product_info.csv')
products.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [3]:
print(products.columns.to_list())
print(products.shape)

['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count', 'rating', 'reviews', 'size', 'variation_type', 'variation_value', 'variation_desc', 'ingredients', 'price_usd', 'value_price_usd', 'sale_price_usd', 'limited_edition', 'new', 'online_only', 'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category', 'secondary_category', 'tertiary_category', 'child_count', 'child_max_price', 'child_min_price']
(8494, 27)

In [4]:
# importing tables 0-250
reviews_0_250 = pd.read_csv('../data/reviews_0-250.csv')
reviews_0_250.head()

/var/folders/_s/x14mjmjn7qj5qh8bhxln436r0000gn/T/ipykernel_86299/1787187751.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_0_250 = pd.read_csv('../data/reviews_0-250.csv')

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,NaN,brown,dry,black,P504322,Gentle Hydra-Gel Face Cleanser,NUDESTIX,19.0
1,1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,NaN,NaN,NaN,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
2,2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,light,brown,dry,blonde,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
3,3,6083038851,5,1.0,NaN,0,0,0,2023-03-20,I’ve always loved this formula for a long time...,Can't go wrong with any of them,NaN,brown,combination,black,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
4,4,47056667835,5,1.0,NaN,0,0,0,2023-03-20,"If you have dry cracked lips, this is a must h...",A must have !!!,light,hazel,combination,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0

In [5]:
print(reviews_0_250.columns.to_list())
print(reviews_0_250.shape)

['Unnamed: 0', 'author_id', 'rating', 'is_recommended', 'helpfulness', 'total_feedback_count', 'total_neg_feedback_count', 'total_pos_feedback_count', 'submission_time', 'review_text', 'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color', 'product_id', 'product_name', 'brand_name', 'price_usd']
(602130, 19)

In [6]:
reviews_250_500 = pd.read_csv('../data/reviews_250-500.csv')
reviews_250_500.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,2190293206,2,0.0,NaN,0,0,0,2023-03-19,Used to swear by this product but hate the sme...,NaN,lightMedium,brown,combination,brown,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99
1,1,9113341005,5,1.0,NaN,0,0,0,2023-03-18,I’ve only been using this for a week and my sk...,More tolerable than The Ordinary,deep,brown,normal,black,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99
2,2,23866342710,1,0.0,1.000000,13,0,13,2023-03-12,"Why, why, why would you change the formula?!!!...",New formula is awful very sad,fairLight,blue,combination,blonde,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99
3,3,1328806527,1,0.0,0.941176,17,1,16,2023-03-12,I have used this product for years and it has ...,Recently reformulated and the new formula is A...,light,brown,combination,gray,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99
4,4,31262847082,5,1.0,1.000000,1,0,1,2023-03-09,Great product for anti-aging Also great for da...,Must have product in my nighttime skincare rou...,lightMedium,hazel,combination,brown,P443842,Retinol Anti-Aging Serum,The INKEY List,12.99

In [7]:
print(reviews_250_500.columns.to_list())
print(reviews_250_500.shape)

['Unnamed: 0', 'author_id', 'rating', 'is_recommended', 'helpfulness', 'total_feedback_count', 'total_neg_feedback_count', 'total_pos_feedback_count', 'submission_time', 'review_text', 'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color', 'product_id', 'product_name', 'brand_name', 'price_usd']
(206725, 19)

In [8]:
reviews_500_750 = pd.read_csv('../data/reviews_500-750.csv')
reviews_500_750.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,2079014373,5,1.0,NaN,0,0,0,2023-03-14,These are the only pimple patches I’ve used th...,Best Pimple Patches,medium,blue,normal,NaN,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
1,1,12631885517,4,1.0,NaN,0,0,0,2023-02-08,One of my ingrown hair turned inflamed and sor...,It works!,mediumTan,brown,combination,black,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
2,2,2321761961,5,1.0,1.0,1,0,1,2023-02-05,I have tried 10 different acne/blemish patches...,Good for a large or painful breakout! Sleep in...,NaN,hazel,combination,blonde,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
3,3,1380382883,4,1.0,NaN,0,0,0,2023-01-24,"Love these for my mid-size breakouts, specifyi...",Micro tips are a plus!!,light,brown,combination,black,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
4,4,8871759068,4,1.0,1.0,1,0,1,2023-01-15,Best so far - though still not particularly ef...,NaN,NaN,NaN,NaN,NaN,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0

In [9]:
reviews_500_750 = pd.read_csv('../data/reviews_500-750.csv')
reviews_500_750.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,2079014373,5,1.0,NaN,0,0,0,2023-03-14,These are the only pimple patches I’ve used th...,Best Pimple Patches,medium,blue,normal,NaN,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
1,1,12631885517,4,1.0,NaN,0,0,0,2023-02-08,One of my ingrown hair turned inflamed and sor...,It works!,mediumTan,brown,combination,black,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
2,2,2321761961,5,1.0,1.0,1,0,1,2023-02-05,I have tried 10 different acne/blemish patches...,Good for a large or painful breakout! Sleep in...,NaN,hazel,combination,blonde,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
3,3,1380382883,4,1.0,NaN,0,0,0,2023-01-24,"Love these for my mid-size breakouts, specifyi...",Micro tips are a plus!!,light,brown,combination,black,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0
4,4,8871759068,4,1.0,1.0,1,0,1,2023-01-15,Best so far - though still not particularly ef...,NaN,NaN,NaN,NaN,NaN,P442857,Focuspot Micro Tip Patches,Dr. Jart+,20.0

In [10]:
reviews_1250_end = pd.read_csv('../data/reviews_1250-end.csv')
reviews_1250_end.head()

/var/folders/_s/x14mjmjn7qj5qh8bhxln436r0000gn/T/ipykernel_86299/573712047.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_1250_end = pd.read_csv('../data/reviews_1250-end.csv')

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1945004256,5,1.0,0.000000,2,2,0,2022-12-10,I absolutely L-O-V-E this oil. I have acne pro...,A must have!,lightMedium,green,combination,NaN,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0
1,1,5478482359,3,1.0,0.333333,3,2,1,2021-12-17,I gave this 3 stars because it give me tiny li...,it keeps oily skin under control,mediumTan,brown,oily,black,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0
2,2,29002209922,5,1.0,1.000000,2,0,2,2021-06-07,Works well as soon as I wash my face and pat d...,Worth the money!,lightMedium,brown,dry,black,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0
3,3,7391078463,5,1.0,1.000000,2,0,2,2021-05-21,"this oil helped with hydration and breakouts, ...",best face oil,lightMedium,brown,combination,blonde,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0
4,4,1766313888,5,1.0,1.000000,13,0,13,2021-03-29,This is my first product review ever so that s...,Maskne miracle,mediumTan,brown,combination,black,P379064,Lotus Balancing & Hydrating Natural Face Treat...,Clarins,65.0

#### Merging tables

In [11]:
# dropping 'Unnamed: 0' column from all tables
reviews_0_250 = reviews_0_250.drop(columns=['Unnamed: 0'])
reviews_250_500 = reviews_250_500.drop(columns=['Unnamed: 0'])
reviews_500_750 = reviews_500_750.drop(columns=['Unnamed: 0'])
reviews_1250_end = reviews_1250_end.drop(columns=['Unnamed: 0'])

**Merging (stacking) all review tables together**

In [12]:
reviews_all = pd.concat([
    reviews_0_250,
    reviews_250_500,
    reviews_500_750,
    reviews_1250_end
], ignore_index=True)

print(reviews_all.shape)
reviews_all.head()

(975094, 18)

,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,NaN,brown,dry,black,P504322,Gentle Hydra-Gel Face Cleanser,NUDESTIX,19.0
1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,NaN,NaN,NaN,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,light,brown,dry,blonde,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
3,6083038851,5,1.0,NaN,0,0,0,2023-03-20,I’ve always loved this formula for a long time...,Can't go wrong with any of them,NaN,brown,combination,black,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
4,47056667835,5,1.0,NaN,0,0,0,2023-03-20,"If you have dry cracked lips, this is a must h...",A must have !!!,light,hazel,combination,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0

In [13]:
# downloading merged reviews to csv file
# reviews_all.to_csv("reviews_all.csv", index=False)

**Merging reviews with product tables**

In [14]:
full_data = pd.merge(
    reviews_all,
    products,
    on='product_id',
    how='left'
)

print(full_data.shape)
full_data.head()

(975094, 44)

,author_id,rating_x,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,...,1,0,0,['Clean at Sephora'],Skincare,Cleansers,NaN,0,NaN,NaN
1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,...,0,0,1,"['allure 2019 Best of Beauty Award Winner', 'C...",Skincare,Lip Balms & Treatments,NaN,3,24.0,24.0
2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,...,0,0,1,"['allure 2019 Best of Beauty Award Winner', 'C...",Skincare,Lip Balms & Treatments,NaN,3,24.0,24.0
3,6083038851,5,1.0,NaN,0,0,0,2023-03-20,I’ve always loved this formula for a long time...,Can't go wrong with any of them,...,0,0,1,"['allure 2019 Best of Beauty Award Winner', 'C...",Skincare,Lip Balms & Treatments,NaN,3,24.0,24.0
4,47056667835,5,1.0,NaN,0,0,0,2023-03-20,"If you have dry cracked lips, this is a must h...",A must have !!!,...,0,0,1,"['allure 2019 Best of Beauty Award Winner', 'C...",Skincare,Lip Balms & Treatments,NaN,3,24.0,24.0

Note: Since we merged the full review tables and products, both tables had rating, product_name, brand_name, and price_usd. So after the merging, pandas automatically assigned:
- From reviews table: rating_x, product_name_x, brand_name_x, price_usd_x
- From products table: rating_y, product_name_y, brand_name_y, price_usd_y

In [16]:
full_data.info()
full_data.isnull().sum()
full_data['rating_x'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 975094 entries, 0 to 975093
Data columns (total 44 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   author_id                 975094 non-null  object
 1   rating_x                  975094 non-null  int64
 2   is_recommended            816002 non-null  float64
 3   helpfulness               465509 non-null  float64
 4   total_feedback_count      975094 non-null  int64
 5   total_neg_feedback_count  975094 non-null  int64
 6   total_pos_feedback_count  975094 non-null  int64
 7   submission_time           975094 non-null  object
 8   review_text               973739 non-null  object
 9   review_title              699996 non-null  object
 10  skin_tone                 819803 non-null  object
 11  eye_color                 780129 non-null  object
 12  skin_type                 871142 non-null  object
 13  hair_color                768883 non-null  object
 14  product_id                975094 non-null  object
 15  product_name_x            975094 non-null  object
 16  brand_name_x              975094 non-null  object
 17  price_usd_x               975094 non-null  float64
 18  product_name_y            975094 non-null  object
 19  brand_id                  975094 non-null  int64
 20  brand_name_y              975094 non-null  object
 21  loves_count               975094 non-null  int64
 22  rating_y                  975094 non-null  float64
 23  reviews                   975094 non-null  float64
 24  size                      938914 non-null  object
 25  variation_type            932354 non-null  object
 26  variation_value           922705 non-null  object
 27  variation_desc            8283 non-null    object
 28  ingredients               957589 non-null  object
 29  price_usd_y               975094 non-null  float64
 30  value_price_usd           28701 non-null   float64
 31  sale_price_usd            8270 non-null    float64
 32  limited_edition           975094 non-null  int64
 33  new                       975094 non-null  int64
 34  online_only               975094 non-null  int64
 35  out_of_stock              975094 non-null  int64
 36  sephora_exclusive         975094 non-null  int64
 37  highlights                879758 non-null  object
 38  primary_category          975094 non-null  object
 39  secondary_category        975094 non-null  object
 40  tertiary_category         822301 non-null  object
 41  child_count               975094 non-null  int64
 42  child_max_price           435028 non-null  float64
 43  child_min_price           435028 non-null  float64
dtypes: float64(10), int64(12), object(22)
memory usage: 327.3+ MB

rating_x
5    620368
4    178283
3     73542
1     55152
2     47749
Name: count, dtype: int64

### Cleaning
---

In [17]:
reviews_all = pd.read_csv('../data/reviews_all.csv')
print(reviews_all.columns.to_list())

['Unnamed: 0', 'author_id', 'rating', 'is_recommended', 'helpfulness', 'total_feedback_count', 'total_neg_feedback_count', 'total_pos_feedback_count', 'submission_time', 'review_text', 'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color', 'product_id', 'product_name', 'brand_name', 'price_usd']

/var/folders/_s/x14mjmjn7qj5qh8bhxln436r0000gn/T/ipykernel_86299/2984699467.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_all = pd.read_csv('../data/reviews_all.csv')

In [18]:
reviews_all_products = pd.read_csv('../data/reviews_all_products.csv')
print(reviews_all_products.columns.to_list())

/var/folders/_s/x14mjmjn7qj5qh8bhxln436r0000gn/T/ipykernel_86299/454649909.py:1: DtypeWarning: Columns (1,28) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_all_products = pd.read_csv('../data/reviews_all_products.csv')

['Unnamed: 0', 'author_id', 'rating_x', 'is_recommended', 'helpfulness', 'total_feedback_count', 'total_neg_feedback_count', 'total_pos_feedback_count', 'submission_time', 'review_text', 'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color', 'product_id', 'product_name_x', 'brand_name_x', 'price_usd_x', 'product_name_y', 'brand_id', 'brand_name_y', 'loves_count', 'rating_y', 'reviews', 'size', 'variation_type', 'variation_value', 'variation_desc', 'ingredients', 'price_usd_y', 'value_price_usd', 'sale_price_usd', 'limited_edition', 'new', 'online_only', 'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category', 'secondary_category', 'tertiary_category', 'child_count', 'child_max_price', 'child_min_price']

In [19]:
# renaming columns in reviews_all_products for clarity
reviews_all_products = reviews_all_products.rename(columns={
    'rating_x': 'review_rating',
    'rating_y': 'product_rating',
    'price_usd_x': 'review_price',
    'price_usd_y': 'product_price',
    'product_name_x': 'product_name',
    'brand_name_x': 'brand_name'
})

In [ ]:
# downloading merged reviews and products to csv file
# reviews_all_products.to_csv("reviews_all_products.csv", index=False)

### Looking into column specific data
---

**User-specific**

In [21]:
reviews_all_products["skin_tone"].unique()

array([nan, 'light', 'lightMedium', 'fairLight', 'fair', 'medium',
       'notSureST', 'mediumTan', 'tan', 'rich', 'olive', 'deep',
       'porcelain', 'dark', 'ebony'], dtype=object)

In [22]:
reviews_all_products["eye_color"].unique()

array(['brown', nan, 'hazel', 'blue', 'green', 'gray', 'Grey'],
      dtype=object)

In [23]:
reviews_all_products["skin_type"].unique()

array(['dry', nan, 'combination', 'normal', 'oily'], dtype=object)

In [24]:
reviews_all_products["hair_color"].unique()

array(['black', nan, 'blonde', 'brown', 'brunette', 'gray', 'auburn',
       'red'], dtype=object)

**Product-specific**

In [25]:
reviews_all_products["primary_category"].unique()

array(['Skincare'], dtype=object)

In [26]:
reviews_all_products["secondary_category"].unique()

array(['Cleansers', 'Lip Balms & Treatments', 'Moisturizers',
       'Treatments', 'Mini Size', 'Masks', 'Sunscreen', 'Eye Care',
       'Self Tanners', 'Value & Gift Sets', 'Wellness', 'High Tech Tools',
       'Shop by Concern'], dtype=object)

In [27]:
reviews_all_products["tertiary_category"].unique()

array([nan, 'Face Wash & Cleansers', 'Face Oils', 'Moisturizers',
       'Facial Peels', 'Makeup Removers', 'Face Serums', 'BB & CC Creams',
       'Exfoliators', 'Blemish & Acne Treatments', 'Face Masks',
       'Face Wipes', 'Mists & Essences', 'Toners', 'Face Sunscreen',
       'Eye Creams & Treatments', 'For Face', 'Night Creams', 'Eye Masks',
       'Beauty Supplements', 'For Body', 'Teeth Whitening', 'Sheet Masks',
       'Holistic Wellness', 'Body Sunscreen', 'Facial Cleansing Brushes',
       'Facial Rollers', 'Anti-Aging', 'Decollete & Neck Creams',
       'Hair Removal', 'Blotting Papers'], dtype=object)

In [28]:
reviews_all_products["highlights"].unique()

array(["['Clean at Sephora']",
       "['allure 2019 Best of Beauty Award Winner', 'Community Favorite', 'Vitamin C', 'Hydrating', 'Good for: Dryness', 'Without Parabens']",
       "['Clean at Sephora', 'Best for Dry, Combo, Normal Skin', 'Hydrating', 'Good for: Dryness', 'Good for: Dullness/Uneven Texture', 'Without Parabens']",
       ...,
       "['Good for: Anti-Aging', 'Good for: Dryness', 'Good for: Dullness/Uneven Texture', 'Without Parabens', 'Vegan', 'Cruelty-Free']",
       "['Best for Dry Skin']", "['Hydrating', 'Without Parabens']"],
      shape=(1276,), dtype=object)